set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(CMAKE_C_COMPILER x86_64-w64-mingw32-gcc)
set(CMAKE_CXX_COMPILER x86_64-w64-mingw32-g++)
set(CMAKE_RC_COMPILER x86_64-w64-mingw32-windres)

set(CMAKE_FIND_ROOT_PATH /usr/x86_64-w64-mingw32 ${CMAKE_PREFIX_PATH})
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

# Use host Qt5 tools for cross-compilation AUTOMOC
set(QT_MOC_EXECUTABLE "/usr/bin/moc" CACHE FILEPATH "moc executable" FORCE)
set(QT_UIC_EXECUTABLE "/usr/bin/uic" CACHE FILEPATH "uic executable" FORCE)
set(QT_RCC_EXECUTABLE "/usr/bin/rcc" CACHE FILEPATH "rcc executable" FORCE)
